### PR TITLE
Update to ospray/release-0.8 and install missing headers

### PR DESCRIPTION
**Pull request by jafyvilla**

### CODE REVIEW

**Comment by bilgili** [comment]
+1
We can send a pull request I think. If they dont merge it we can move to "bbp" branch.

**Comment by favreau** [comment]
Can we merge this PR?

**Comment by jafyvilla** [comment]
I guess we can, if no one disagrees with the change

PS: I can't, so feel free to do it if you are fine with it

**Comment by bilgili** [comment]
I am merging !

**Pull request merged**
